name: aa_travel_planner
description: "Eine mittelgroße App, die das Finden von Zielen und Reisen simuliert."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.4.1

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1


flutter:
  uses-material-design: true
  assets:
    - assets/images/
